wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1677691857.174023
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.9.6
      5: 0.13.10
      8:
      - 5
