name: Build docs

# Runs on pushes targeting the default branch
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

# Cancel in-progress runs when pushing a new commit on the PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip' # caching pip dependencies

      - name: Comment on PR with preview url
        uses: mshick/add-pr-comment@v2
        if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' }}
        with:
          message: |
            Documentation preview for this PR at format('https://deepinv.github.io/pr-preview/pr-preview/pr-{0}', github.event.pull_request.number)
      - name: Install deepinv and its dependencies
        run: |
          pip install -e .[dataset,denoisers,doc]
      - name: Sphinx build
        run: |
          sphinx-build -W docs/source _build
      - name: Run doctests
        run: |
          # Get all the RST files, excluding multigpu.rst
          # and *datasets.rst files
          _doctest_files=$(find . -name '*.rst' ! -name '*multigpu.rst' ! -name '*datasets*.rst')
          # Run doctest with sphinx, to get the extra IGNORE_OUTPUT primitive
          # using plot_gallery=0 to avoid building examples
          sphinx-build -M doctest docs/source/ docs/build/ -D plot_gallery=0 -v $_doctest_files
      - name: Deploy PR Docs to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'pull_request' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _build/
          destination_dir: ${{ github.event_name == 'pull_request' && format('pr-preview/pr-{0}', github.event.pull_request.number) || '' }}
          keep_files: true
          enable_jekyll: false
          force_orphan: false      
          